CREATE DATABASE DB_KHOAHOC_ONLINE
USE DB_KHOAHOC_ONLINE

-- BẢNG QUẢN TRỊ HỆ THỐNG


--CREATE TABLE TAIKHOAN

CREATE TABLE VAITRO
(
	ID INT PRIMARY KEY,
	TENVAITRO NVARCHAR(255),
)
CREATE TABLE NGUOIDUNG 
(
	ID INT PRIMARY KEY,
	TENDANGNHAP NVARCHAR(255),
	MATKHAU NVARCHAR(255),
	VAITRO_ID INT,
	FOREIGN KEY(VAITRO_ID) REFERENCES VAITRO(ID),

)

-- BẢNG GIẢNG VIÊN
CREATE TABLE GIANGVIEN
(
	ID INT PRIMARY KEY,
	TENGV NVARCHAR (255),
	MOTA NVARCHAR (255),
	GIOITHIEU NVARCHAR (255),
	TONGKHOAHOC INT, 
	TONGHOCVIEN INT,
	LINK VARCHAR (255),
	AVATA VARCHAR (255),
	DIACHI NVARCHAR (255),
	NGAYSINH NVARCHAR (255),
	SDT VARCHAR(255),
	CMND VARCHAR(255),
	
)


-- BẢNG HỌC VIÊN
CREATE TABLE HOCVIEN 
(
	ID INT PRIMARY KEY,
	TENHV NVARCHAR(255),
	AVATA VARCHAR(255),
	DIACHI NVARCHAR(255),
	NGAYSINH NVARCHAR(255),
	
)

ALTER TABLE HOCVIEN
ADD NGUOIDUNG_ID INT;

ALTER TABLE GIANGVIEN
ADD NGUOIDUNG_ID INT;

ALTER TABLE HOCVIEN
ADD CONSTRAINT FK_HOCVIEN_NGUOIDUNG
FOREIGN KEY (NGUOIDUNG_ID)
REFERENCES NGUOIDUNG(ID);


ALTER TABLE GIANGVIEN
ADD CONSTRAINT FK_GIANGVIEN_NGUOIDUNG
FOREIGN KEY (NGUOIDUNG_ID)
REFERENCES NGUOIDUNG(ID);

-- CÁC TABLE DÀNH CHO KHÓA HỌC

-- BẢNH DANH MỤC KHÓA HỌC
CREATE TABLE DANHMUCKHOAHOC
(
	ID INT PRIMARY KEY,
	TENDANHMUC NVARCHAR(255),
)
-- BẢNG KHÓA HỌC
CREATE TABLE KHOAHOC 
(
	ID INT PRIMARY KEY, 
	TIEUDE NVARCHAR (255), 
	GIA FLOAT, 
	GIAGIAM FLOAT,
	IMG VARCHAR (255),
	TONGTHOIGIAN VARCHAR(255),
	TONGSOCHUONG INT, 
	DANHMUCKHOAHOC_ID INT,
	GIANGVIEN_ID INT,
	FOREIGN KEY(DANHMUCKHOAHOC_ID) REFERENCES DANHMUCKHOAHOC(ID),
	FOREIGN KEY(GIANGVIEN_ID) REFERENCES GIANGVIEN(ID),


)
CREATE TABLE CHUONGKHOAHOC
(
	ID INT PRIMARY KEY, 
	KHOAHOC_ID INT,
	TENCHUONG NVARCHAR(255),
	FOREIGN KEY(KHOAHOC_ID) REFERENCES KHOAHOC(ID),

)
CREATE TABLE NOIDUNGKHOAHOC
(
	ID INT,
	TIEUDENOIDUNG NVARCHAR(255),
	VIDEO VARCHAR(255),
	CHUONGKHOAHOC_ID INT,
	FOREIGN KEY(CHUONGKHOAHOC_ID) REFERENCES CHUONGKHOAHOC(ID),
)

CREATE TABLE DANHGIA 
(
	ID INT PRIMARY KEY,
	SOSAO  NVARCHAR(255),
	NOIDUNG NVARCHAR(255),
	HOCVIEN_ID INT,
	FOREIGN KEY (HOCVIEN_ID) REFERENCES HOCVIEN(ID),
	KHOAHOC_ID INT, 
	FOREIGN KEY(KHOAHOC_ID) REFERENCES KHOAHOC(ID),
)

--- CAC BANG VE HOC VIEN MUA VA HOC KHOA HOC
CREATE TABLE PTTHANHTOAN
(
	ID INT PRIMARY KEY,
	HINHTHUCTHANHTOAN NVARCHAR
)
CREATE TABLE HOADON
(
	ID INT PRIMARY KEY, 
	TONGTIEN FLOAT, 
	NGAYTHANHTOAN DATE,
	PTTHANHTOAN_ID INT,
	FOREIGN KEY (PTTHANHTOAN_ID) REFERENCES PTTHANHTOAN(ID),
	

)
ALTER TABLE HOADON
ADD HOCVIEN_ID INT;

ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_HOCVIEN
FOREIGN KEY (HOCVIEN_ID)
REFERENCES HOCVIEN(ID);

CREATE TABLE CHITIETHOADON
(
	KHOAHOC_ID INT,
	HOADON_ID INT,
	NGAYMUA DATE,
	PRIMARY KEY (KHOAHOC_ID, HOADON_ID),
	FOREIGN KEY (KHOAHOC_ID) REFERENCES KHOAHOC(ID),
	FOREIGN KEY (HOADON_ID) REFERENCES HOADON(ID),



)
CREATE TABLE GIOHANG
(
	ID INT PRIMARY KEY,
	HOCVIEN_ID INT,
	KHOAHOC_ID INT,
	TONGTIEN FLOAT,
	FOREIGN KEY (HOCVIEN_ID) REFERENCES HOCVIEN(ID),
	FOREIGN KEY (KHOAHOC_ID) REFERENCES KHOAHOC(ID),
)



CREATE TABLE KHOAHOCDAMUA
(
	KHOAHOC_ID INT,
	HOCVIEN_ID INT,
	PRIMARY KEY (HOCVIEN_ID, KHOAHOC_ID),
	FOREIGN KEY (HOCVIEN_ID) REFERENCES HOCVIEN(ID),
	FOREIGN KEY (KHOAHOC_ID) REFERENCES KHOAHOC(ID),
)
--CREATE TABLE TIENTRINHHOC 
--(
	
	
--    ID INT PRIMARY KEY,
--    KHOAHOCDAMUA_ID INT, -- Liên kết với bảng KHOAHOCDAMUA
--    BAIHOC_ID INT, -- Liên kết với bảng LESSON hoặc bất kỳ bảng nào lưu trữ thông tin bài học
--    DIEM FLOAT,
--    NGAYHOANTH
--)


